name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      SSH_KEY_PUB: ${{ secrets.SSH_KEY_PUB }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          mkdir -p ~/.ssh/
          # echo ${SSH_KEY_PUB} > ~/.ssh/id_ed25519.pub
          # chmod 600 ~/.ssh/id_ed25519.pub
          # echo ${SSH_KEY} > ~/.ssh/id_ed25519
          # chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -t ed25519 -C '' -f "`pwd`/.ssh/id_ed25519" -N ''
          echo "`cat ~/.ssh/id_ed25519.pub`"
          echo "`cat ~/.ssh/id_ed25519`"
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST }} > ~/.ssh/known_hosts
          scp -P ${{ secrets.SSH_PORT }} -i ~/.ssh/id_ed25519 ./LICENSE.md ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/
      - run: echo "üçè This job's status is ${{ job.status }}."
